wechat_id: gh_9e40313f1f8b  #replace this with your wechat id
help_message: 泡面泡面！
welcome_message:
  title: 功能还在开发中= =
  picture: http://162.105.30.186/members/lichong/lichong.jpg
  description: 欢迎您关注微信泡面小超人
  link: http://162.105.30.186/members/lichong/index.html
